// SPDX-License-Identifier: GPL-3.0-or-later

// Declaring the commands makes Tauri check each one against a capability, so a
// command registered without a grant cannot be called from the webview.
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "confirm_and_open_url",
            "save_file_native",
            "import_file_native",
            "select_db_file",
            "show_alert_dialog",
            "notes_boot",
            "notes_import_local",
            "notes_connect",
            "notes_disconnect",
            "notes_sync_structure",
            "notes_trash",
            "notes_restore",
            "notes_empty_trash",
            "notes_vacuum",
            "doc_push",
            "doc_pull",
            "get_mcp_connection_info",
            "start_mcp_server",
            "set_mcp_permissions",
            "stop_mcp_server",
            "clip_list",
            "clip_reveal",
            "clip_select",
            "clip_delete",
            "clip_close",
            "clip_shown",
            "clip_hidden",
            "clip_start_drag",
            "clip_set_config",
            "clip_set_theme",
            "quit_handler_ready",
            "quit_window_done",
            "open_accessibility_settings",
            "qn_close",
            "qn_start_drag",
            "qn_get_config",
            "qn_set_hotkey",
            "qn_dismiss_intro",
            "qn_show",
            "show_main_window",
            "file_open_dialog",
            "file_save_as_dialog",
            "file_read",
            "file_write",
            "file_lists",
            "file_set_open",
            "file_take_pending",
            "file_forget_recent",
            "file_confirm_discard",
        ]),
    ))
    .expect("failed to run tauri-build");
}
