// SPDX-License-Identifier: GPL-3.0-or-later
// Copies Mermaid's prebuilt split ESM build into src/vendor/mermaid/. The ELK layout chunk
// (elkjs, EPL-2.0) is left out; see docs/superpowers/specs/2026-10-06-mermaid-diagrams-design.md.

import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const distUrl = new URL("../node_modules/mermaid/dist/", import.meta.url);
const chunksUrl = new URL("chunks/mermaid.esm.min/", distUrl);
const targetUrl = new URL("../src/vendor/mermaid/", import.meta.url);
const targetChunksUrl = new URL("chunks/mermaid.esm.min/", targetUrl);

const { version } = JSON.parse(await readFile(new URL("../package.json", distUrl), "utf8"));
const banner = `// Generated by scripts/vendor-mermaid.mjs from mermaid ${version}. MIT licensed; see THIRD_PARTY_NOTICES.md.\n`;
const withoutSourceMap = source => source.replace(/\n?\/\/# sourceMappingURL=\S+\s*$/, "\n");

await rm(fileURLToPath(targetUrl), { recursive: true, force: true });
await mkdir(fileURLToPath(targetChunksUrl), { recursive: true });

const entry = await readFile(new URL("mermaid.esm.min.mjs", distUrl), "utf8");
await writeFile(new URL("mermaid.esm.min.mjs", targetUrl), banner + withoutSourceMap(entry));

let copied = 0;
for (const name of await readdir(fileURLToPath(chunksUrl))) {
  if (!name.endsWith(".mjs") || name.startsWith("elk-")) continue;
  const source = await readFile(new URL(name, chunksUrl), "utf8");
  await writeFile(new URL(name, targetChunksUrl), withoutSourceMap(source));
  copied += 1;
}

console.log(`Vendored mermaid ${version} (${copied} chunks, ELK left out)`);
